7.9 原版本5.0.6
wisdommen/UltiTools pull request #50
Opened 2021-07-09 11:45 UTC by Shpries

1.加入了飞行指令  文件：FlyCommands.java
备注：在onEnable使用了动态注册，中英文描述已添加，enable相关已添加，配置文件版本号变化：3.24 -> 3.25

2021-07-09 11:57 UTC, wisdommen requested changes
请把我标注的那些更改一下

2021-07-09 11:57 UTC, wisdommen commented on src/main/resources/en.yml
> +fly_function: 'Fly Command'
改成Fly Function

2021-07-09 11:57 UTC, wisdommen commented on src/main/resources/zh.yml
> +fly_function: 飞行指令
改成飞行指令功能

2021-07-09 11:57 UTC, wisdommen commented on src/main/java/com/ultikits/ultitools/commands/FlyCommands.java
> +            if(sender.hasPermission("ultitools.fly")) {
权限改成ultikits.tools.command.fly

2021-07-09 11:57 UTC, wisdommen commented on src/main/java/com/ultikits/ultitools/commands/FlyCommands.java
> +            if(sender.hasPermission("ultitools.fly")) {
权限改成ultikits.tools.command.fly

2021-07-09 11:57 UTC, wisdommen commented on src/main/java/com/ultikits/ultitools/commands/FlyCommands.java
> +                sender.sendMessage(ChatColor.YELLOW + "已打开飞行");
文本需要在多语言哪里注册上，代码里不要出现具体的语言文字

2021-07-09 11:57 UTC, wisdommen commented on src/main/java/com/ultikits/ultitools/commands/FlyCommands.java
> +                sender.sendMessage(ChatColor.RED + "你没有使用该指令的权限");
文本需要在多语言哪里注册上，代码里不要出现具体的语言文字

2021-07-09 11:57 UTC, wisdommen commented on src/main/java/com/ultikits/ultitools/commands/FlyCommands.java
> +                sender.sendMessage(ChatColor.YELLOW + "已关闭飞行");
文本需要在多语言哪里注册上，代码里不要出现具体的语言文字

2021-07-09 11:57 UTC, wisdommen commented on src/main/java/com/ultikits/ultitools/commands/FlyCommands.java
> +                sender.sendMessage(ChatColor.RED + "你没有使用该指令的权限");
文本需要在多语言哪里注册上，代码里不要出现具体的语言文字

2021-07-09 11:58 UTC, wisdommen commented on src/main/resources/en.yml
> +fly_function: 'Fly Command'
Fly Command Function

2021-07-09 12:03 UTC, qianmo2233 commented on src/main/resources/en.yml
> +fly_function: 'Fly Command'
啊这

2021-07-10 02:19 UTC, wisdommen approved these changes
ok了

2021-07-10 02:20 UTC, merged